Updatee node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -50,7 +50,7 @@ jobs:
 
       - name: Install Shopify CLI
         run: npm install -g @shopify/cli@latest
-        
+
       - name: Check running containers
         run: docker ps
 
@@ -58,35 +58,47 @@ jobs:
         run: docker logs ngrok-container
 
       - name: Get ngrok URL
+        id: get_ngrok_url
         run: |
           curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > ngrok_url.txt
 
       - name: Print ngrok URL
         run: cat ngrok_url.txt
 
-      - name: Stop existing Shopify tunnel
-        run: shopify app tunnel stop
-      
-  
-      
-      - name: Start Shopify tunnel and capture URL
-        run: |
-            shopify app tunnel start &
-            sleep 10 # Wait for tunnel to start
-            curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > shopify_tunnel_url.txt
-            
-  
-      - name: Print Shopify tunnel URL
-        run: cat shopify_tunnel_url.txt
-
       - name: Verify ngrok tunnel
+        id: verify_tunnel
         run: |
           NGROK_URL=$(cat ngrok_url.txt)
           echo "Verifying ngrok tunnel at $NGROK_URL"
-          curl -s -I $NGROK_URL | head -n 1
+          response=$(curl -s -I $NGROK_URL)
+          echo $response
+          if [[ "$response" == *"200 OK"* ]]; then
+            echo "Tunnel is working"
+          else
+            echo "Tunnel failed" && exit 1
+          fi
+
+      - name: Restart ngrok tunnel if needed
+        if: failure()
+        run: |
+          docker stop ngrok-container
+          docker rm ngrok-container
+          docker run --net=host -d --name ngrok-container -e NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTH_TOKEN }} ngrok/ngrok:latest http 9000
+          sleep 10 # Wait for ngrok to start
+          curl -s http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url > ngrok_url.txt
+
+      - name: Print new ngrok URL
+        if: failure()
+        run: cat ngrok_url.txt
 
       - name: Check SonarQube status via ngrok
         run: |
           NGROK_URL=$(cat ngrok_url.txt)
           echo "Checking SonarQube status at $NGROK_URL"
           curl -s -I "$NGROK_URL/api/system/status" | head -n 1
+
+      - name: Test access to SonarQube via ngrok
+        run: |
+          NGROK_URL=$(cat ngrok_url.txt)
+          echo "Testing access to SonarQube via $NGROK_URL"
+          curl -s "$NGROK_URL/api/system/status" | jq .
